### ISSUE TITLE
Using single document collection and compound partition key

### ISSUE THREAD

**Issue by badcop666** [dlmelendez/identitydocumentdb#10]
Hi David, firstly really appreciate the work you've put into this. I've already built a user store, login, password hashing and Jwt token services - then found your library when researching the Asp.Net identity and store provider model.  

I've rolled all my entities into a single collection using a compound partion key "pkey" which starts with the entity type name. I've simply added "Entity" as a base class into your inheritance chain for the Models, it contains an abstract string getter "pkey" - each class can then implement it's own compound string from its own members. the base class Entity takes care of adding the instance typename as a prefix.

The immediate benefit of this is being able to easily browse a mixture of records in the collection.  I have yet to load test this approach - querying tens or hundreds of thousands of records. 

The cost of each separate partition made me decide to try putting all my relatively static entities into the same partition - users, organizations, roles, inventory, etc

Apologies for polluting your issues list with this - if you have time would appreciate any suggestions or thoughts around this.

Regards
Andy Welch, NZ

**Comment by dlmelendez** [comment]
Important! This package should be upgraded to the ElCamino.AspNetCore.Identity.AzureTable package. Check here https://dlmelendez.github.io/identityazuretable/#/migration for data migration information.
