### ISSUE TITLE
Error with user.SelfLink

### ISSUE THREAD

**Issue by jormabs** [dlmelendez/identitydocumentdb#8]
Hi, I get an error in this line Into **ExternalLoginConfirmation** Method in **AccountController**:

result = await _userManager.AddLoginAsync(user, info);

Looking at source files, It seems that the property **user.SelfLink** is null into **UpdateAsync** Method.

Thanks.

**Comment by dlmelendez** [comment]
Yes, this is a bug. The problem is the self link is needed for the update but the CreateAsync() on the usermanager does not return that value with the user object. Try this for a workaround on the AccountController on line 415
`
                        user = await UserManager.FindByIdAsync(user.Id);
`

**Comment by LyndseyPaxton** [comment]
Adding
`var user = new ApplicationUser { UserName = model.Email, Email = model.Email };`

Immediately before 
`var result = await _userManager.CreateAsync(user);`

Worked for me

**Comment by dlmelendez** [comment]
Important! This package should be upgraded to the ElCamino.AspNetCore.Identity.AzureTable package. Check here https://dlmelendez.github.io/identityazuretable/#/migration for data migration information.
